#!/bin/bash
# repsit-z-alpha1


# define some package lists.
# Single packages can be added to the menu without being defined here,
# but both package lists and single packages need to be added to the
# zenity menu around line 60 and to the if/then list around line 75. 
dvd_set=(libdvdcss2 libdvdnav4 libdvdread4)
file_share=(samba smbfs smbclient)
graphics=(gimp blender inkscape)

# for testing
echo "---"
echo "${dvd_set[@]}"
echo "${file_share[@]}"
echo "${graphics[@]}"
echo "---"


zenity --question --ok-label=Yes --cancel-label=No --text="The package list needs to be updated before installing anything. If it's been awhile since you've done that, you should answer \"yes\" to do it now. After the list is updated, aptitude will show you what packages are scheduled for security updates. This will be a simulated run, so answering yes or no will just return you to this script.
    
  Update package list? "
    if [[ $? = 0 ]] ; then
             aptitude update
 #            aptitude -s full-upgrade
             read -p "  Press the ENTER key when you're ready to proceed."
             sleep 1
    fi
 

# This needs to be added in later.   
:<<HOLD
        printf "\n  If any packages were listed for installation in the last
  step, you should upgrade them now by answering \"yes\".
    

  Install security updates? "
    read ans
    case $ans in
      [Yy]*) aptitude -s full-upgrade ; break ;;
      [Nn]*) break ;;
    esac
    
    echo "And then the next thing."
    
    exit 0
HOLD


:<<ProbablyUseless
	zenity --info --text=" FIX THIS TEXT
  Select package groups by the number to get more information about them.
  You will be asked if you want to add them to the installation list or not.
  When you're ready to install the packages, select \"install\".
  If you want to exit this script without installing anything, select
  \"exit\".\n\n"
ProbablyUseless


#ans=$(zenity  --list  --text "Choose package groups to install" --checklist  --column "Pick" --column "options" FALSE "dvd_set" FALSE "file_share" FALSE "graphics" --column "description" "desc 1" "desc 2" "desc 3") ; echo "$ans"

ans=$(zenity --list --title="Installation Menu" --text "Choose package groups to install" --checklist \
  --column "Pick" --column "Package Group" --column "Description" \
  FALSE dvd_set description1 \
  FALSE file_share description2 \
  FALSE graphics description3)
echo "$ans"


# this needs to be here in case the list is cancelled or ok'd with no selections.
if [[ -z $ans ]]; then
    exit 0
fi

# This is kind of ugly, but it works. Or at least it ends up showing the right packages.
if $(echo $ans | grep -q dvd_set) ; then
    install_list=("${install_list[@]}"  "${dvd_set[@]}")
fi
if $(echo $ans | grep -q file_share) ; then
    install_list=("${install_list[@]}"  "${file_share[@]}")
fi
if $(echo $ans | grep -q graphics) ; then
    install_list=("${install_list[@]}"  "${graphics[@]}")
fi

echo "${install_list[@]}"


# this was a dead-end
#for i in "$ans"; do
#    echo "${i[@]}"
#     echo "x$ix"
#done

# Don't quote the array here, or aptitude will puke.
	echo "==="
	aptitude -s install ${install_list[@]}
	exit 0

