#!/usr/bin/env bash
# repsit-zenity
# copyright 2011 fsmithred@gmail.com
# License: GPL-3

# NOTES: 1. Installation of update-manager-gnome hangs (running iso in vbox) on "Processing triggers for gconf2" in refracta-6-beta
#        and in my own live-squeeze build. SKIP THE UPDATE WHEN IT ASKS! (unless you already have update-manager installed or you want to test.)
#        2. This one really installs stuff if you tell it to. *** aptitude -y blah ***
#        3. Seems to work properly in an installed system in vbox (my live-squeeze).

# define some package lists.
# If you add a package list here, you must also add it to the
# zenity list around line 35 and to the if/then list around line 50.
# Note that a list can contain one or more packages. 
dvd_set=(libdvdcss2 libdvdnav4 libdvdread4)
file_share=(samba smbfs smbclient)
graphics=(gimp blender inkscape)
mousepad=(mousepad)

# Check that user is root.
[[ $(id -u) -eq 0 ]] || { printf "\t You need to be root!\n" ; exit 1 ; }


zenity --question  --ok-label=OK --cancel-label="Skip update" \
  --text="Before installing new software, the system should be updated. If you haven't done this recently (i.e. in the last 24 hours) you should click OK to proceed. 
  
Click OK to proceed, or Cancel to skip the update." 

if [[ $? = 0 ]] ; then
    if [[ $(type -p update-manager) ]] ; then
        update-manager
    else
        zenity --question  --ok-label=Yes --cancel-label=No --text="Update Manager is not installed. If you don't install it, you need to run the updates manually. In either case, you'll need to run this installer again.
        
Install update-manager-gnome now?"
        if [[ $? = 0 ]] ; then
            aptitude -y install update-manager-gnome | tee >(zenity --progress --pulsate)
            exit 0
        else
            exit 0
        fi
    fi
fi

ans=$(zenity --list --title="Installation Menu" --text "Choose package groups to install" --checklist \
  --column "Pick" --column "Package Group" --column "Description" \
  FALSE dvd_set "watch dvd movies" \
  FALSE file_share "share files with windows computers" \
  FALSE graphics "programs for editing pictures and movies" \
  FALSE mousepad "graphical text editor for Xfce based on Leafpad")
echo "$ans"


# this needs to be here in case the list is cancelled or ok'd with no selections.
if [[ -z $ans ]]; then
    exit 0
fi

# This is kind of ugly, but it works. Or at least it ends up showing the right packages.
if $(echo $ans | grep -q dvd_set) ; then
    install_list=("${install_list[@]}"  "${dvd_set[@]}")
fi
if $(echo $ans | grep -q file_share) ; then
    install_list=("${install_list[@]}"  "${file_share[@]}")
fi
if $(echo $ans | grep -q graphics) ; then
    install_list=("${install_list[@]}"  "${graphics[@]}")
fi
if $(echo $ans | grep -q mousepad) ; then
    install_list=("${install_list[@]}"  "${mousepad[@]}")
fi

echo "${install_list[@]}"

zenity --question --text="$(aptitude -s install ${install_list[@]} &)"
if [[ $? = 0 ]] ; then
    aptitude -y install ${install_list[@]}  | tee >(zenity --progress --pulsate)
else
    echo "You said no."
    exit 0
fi

exit 0
