#!/usr/bin/env bash
# zinstaller-test4
# Copyright 2011 fsmithred@gmail.com
# License: GPL-3
# This is free software with NO WARRANTY. Use at your own risk!
#
# TEST VERSION - it does nothing for real; it just shows you stuff.
# It will also allow you to try to install to an extended partition. Hm...

error_log="z4error_log.txt"
exec 2>"$error_log"

###rsync_excludes="/home/user/exclude.list"

# function to exit the script if there are errors
check_exit () {
[[ $? -eq 0 ]] || { echo "Exit due to error:  $?" ; exit 1 ; }
}

# Check that user is root.
###[[ $(id -u) -eq 0 ]] || { echo -e "\t You need to be root!\n" ; exit 1 ; }

#:<<HOLD
zenity --question --ok-label=Yes --cancel-label=No \
    --text=" You need to have a partition ready for the installation. If you 
 haven't already done that, you can run the partition editor now.
 If you want a separate /home partition, you should create it at 
 this time, this script will ask you later if you've done that.
 
 Run GParted Partition Editor now?"
if [[ $? = 0 ]] ; then
#    gparted
    xterm -hold -e echo "    Pretend you're running gparted now. Close the
    xterm when you're ready to proceed."
fi
#HOLD

# Find hard drives, and choose one for grub
grub_dev=$(find /dev -mindepth 1 -maxdepth 1  -name "*[sh]d[a-z]"  -printf 'FALSE\0%p\0' |
xargs -0 zenity --list --checklist --multiple --column ' ' --column 'Hard Drives')

if [[ -z $grub_dev ]] ; then
    echo "No bootloader will be installed. Are you sure you want this?"
    sleep 2 
elif ! [[ -b $grub_dev ]] ; then
    echo "Something is wrong. Maybe you checked
    more than one box. If this were a real install,
    this script would not let you proceed."
    sleep 3
elif [[ -b $grub_dev ]] ; then
    echo "GRUB bootloader will be installed on $grub_dev"
    sleep 2
fi

sleep 2


# Show the partition list in a menu, and choose one for the OS
install_dev=$(find /dev -mindepth 1 -maxdepth 1  -name "*[sh]d[a-z][0-9]"  -printf 'FALSE\0%p\0' | \
xargs -0 zenity --list --text="Choose exactly one partition to use for the installation of the operating system." \
--checklist --multiple --column ' ' --column 'Partitions')

#[[ -b $install_dev ]] || { echo "$install_dev does not exist!" ; exit 1 ; }
if ! [[ -b $install_dev ]] ; then
    echo "Something is wrong. Maybe you checked
    more than one box. If this were a real install,
    this script would not let you proceed."
    sleep 3
else
    echo "  OS will be installed on $install_dev
  Even better would be a summary window at the end of the selection
  process to tell you what's going to happen."
fi

sleep 2

# Show the partition list in a menu, and choose one for /home
home_dev=$(find /dev -mindepth 1 -maxdepth 1  -name "*[sh]d[a-z][0-9]"  -printf 'FALSE\0%p\0' | \
xargs -0 zenity --list --text="Choose exactly one partition to use for /home" \
--checklist --multiple --column ' ' --column 'Partitions')

if ! [[ -b $home_dev ]] ; then
    echo "Something is wrong. Maybe you checked
    more than one box. If this were a real install,
    this script would not let you proceed."
    sleep 3
else
    echo "/home will be installed on $home_dev"
fi

sleep 2

if [[ $install_dev = $home_dev ]] ; then
    echo "
    If you want to install /home on the same partition
    as the operating system, you should have said so earlier.
    Exiting...
    "
    exit 1
fi

echo "-----------------
   If you're seeing this message, you got to the end of the script.
================"

exit 0
