#!/usr/bin/env bash
# zinstaller-test5
# Copyright 2011 fsmithred@gmail.com
# License: GPL-3
# This is free software with NO WARRANTY. Use at your own risk!
#
# TEST VERSION - it does nothing for real; it just shows you stuff.
# It will also allow you to try to install to an extended partition. Hm...

error_log="z5error_log.txt"
exec 2>"$error_log"

###rsync_excludes="/home/user/exclude.list"

# function to exit the script if there are errors
check_exit () {
[[ $? -eq 0 ]] || { echo "Exit due to error:  $?" ; exit 1 ; }
}

# Check that user is root.
###[[ $(id -u) -eq 0 ]] || { echo -e "\t You need to be root!\n" ; exit 1 ; }

zenity --question --ok-label=Yes --cancel-label=No \
    --text=" You need to have a partition ready for the installation. If you 
 haven't already done that, you can run the partition editor now.
 If you want a separate /home partition, you should create it at 
 this time, this script will ask you later if you've done that.
 
 Run GParted Partition Editor now?"
if [[ $? = 0 ]] ; then
#####    gparted
    xterm -hold -e echo "    Pretend you're running gparted now. Close the
    xterm when you're ready to proceed."
fi

echo "one"
# Find hard drives, and choose one for grub
choose_grub () {
grub_dev=$(find /dev -mindepth 1 -maxdepth 1  -name "*[sh]d[a-z]"  -printf 'FALSE\0%p\0' |
xargs -0 zenity --list --text="Choose a location to install the bootloader." --checklist --multiple --column ' ' --column 'Hard Drives')

if [[ -z $grub_dev ]] ; then
    zenity --question  --ok-label="Yes, I'm sure." --cancel-label="Go back" \
  --text="No bootloader will be installed. Are you sure you want this?"
        if [[ $? != 0 ]] ; then
            choose_grub
        fi
elif ! [[ -b $grub_dev ]] ; then
    zenity --question  --ok-label=Exit --cancel-label="Go back" \
  --text="    Something is wrong. Maybe you checked
    more than one box. You said you want to install
    the bootloader in $grub_dev"
        if [[ $? = 0 ]] ; then
            exit 1
        else
            choose_grub
        fi
fi
}

choose_grub

echo "two"
# Show the partition list in a menu, and choose one for the OS
choose_root () {
install_dev=$(find /dev -mindepth 1 -maxdepth 1  -name "*[sh]d[a-z][0-9]"  -printf 'FALSE\0%p\0' | \
xargs -0 zenity --list --text="Choose exactly one partition to use for the installation of the operating system." \
--checklist --multiple --column ' ' --column 'Partitions')

if [[ -z $install_dev ]] ; then
    zenity --question  --ok-label=Exit --cancel-label="Go back" \
  --text="Nothing was selected. You must select a partition
for the installation. What would you like to do?"
        if [[ $? = 0 ]] ; then
            exit 1
        else
            choose_root
        fi
elif ! [[ -b $install_dev ]] ; then
    zenity --question  --ok-label=Exit --cancel-label="Go back" \
  --text="    Something is wrong. Maybe you checked
    more than one box. You said you want to install
    the system to $install_dev"
        if [[ $? = 0 ]] ; then
            exit 1
        else
            choose_root
        fi
fi
}

choose_root

# Show the partition list in a menu, and choose one for /home
choose_home () {
home_dev=$(find /dev -mindepth 1 -maxdepth 1  -name "*[sh]d[a-z][0-9]"  -printf 'FALSE\0%p\0' | \
xargs -0 zenity --list --text="If you would like a separate /home partition, select 
one now and click \"OK\". Otherwise, just click \"OK\"" \
--checklist --multiple --column ' ' --column 'Partitions')
if [[ -n $home_dev ]] ; then
    if ! [[ -b $home_dev ]] ; then
        zenity --question  --ok-label=Exit --cancel-label="Go back" \
        --text="    Something is wrong. Maybe you checked
    more than one box. You said you want to install
    the system to $home_dev"
        if [[ $? = 0 ]] ; then
            exit 1
        else
            choose_home
        fi
    elif
        [[ $install_dev = $home_dev ]] ; then
        zenity --info --text="    You chose the same partition for /home as the one 
    for the operating system. If you don't want a separate
    /home partition, then click OK without selecting one."
        choose_home
    fi
fi
}
echo "three"

choose_home

if [[ -z $grub_dev ]] ; then
    grub_dev_message="Bootloader will not be installed."
else
    grub_dev_message="Bootloader will be installed in $grub_dev"
fi

if [[ -z $home_dev ]] ; then
    home_dev_message="/home will not be on a separate partition."
else
    home_dev_message="/home will be installed on $home_dev"
fi

zenity --question --ok-label="Proceed with the installation." --cancel-label="Exit" \
    --text="Here is a summary of what will be done. This is your last chance
to bail out before any changes are made.

$grub_dev_message
Operating system will be installed on $install_dev
$home_dev_message"
    if [[ $? != 0 ]] ; then
        exit 0
    fi

# This won't pulsate, and I'm not sure why.
#aptitude search geany | tee >(zenity --progress --pulsate) 



echo "-----------------
   If you're seeing this message, you got to the end of the script.
================"

exit 0
